// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_HLp7oHEx9X800zfP5RS-fJWr4RNeF4',
    appId: '1:347609693914:web:163454a48f2c0010586fe3',
    messagingSenderId: '347609693914',
    projectId: 'estoque-7d7bf',
    authDomain: 'estoque-7d7bf.firebaseapp.com',
    storageBucket: 'estoque-7d7bf.appspot.com',
    measurementId: 'G-4LDBXMNXH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoq6hT1AyLqDDG1TUVOKX5tQsEP700NRQ',
    appId: '1:347609693914:android:200e39e1f558d9aa586fe3',
    messagingSenderId: '347609693914',
    projectId: 'estoque-7d7bf',
    storageBucket: 'estoque-7d7bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE4iWEDNB7X4yg1aG0ILNgwf6UojHOYe0',
    appId: '1:347609693914:ios:299ead653e3ece36586fe3',
    messagingSenderId: '347609693914',
    projectId: 'estoque-7d7bf',
    storageBucket: 'estoque-7d7bf.appspot.com',
    iosClientId: '347609693914-b0gsrm8v2t0260f0anl388cen9a1jsek.apps.googleusercontent.com',
    iosBundleId: 'com.example.estoque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE4iWEDNB7X4yg1aG0ILNgwf6UojHOYe0',
    appId: '1:347609693914:ios:299ead653e3ece36586fe3',
    messagingSenderId: '347609693914',
    projectId: 'estoque-7d7bf',
    storageBucket: 'estoque-7d7bf.appspot.com',
    iosClientId: '347609693914-b0gsrm8v2t0260f0anl388cen9a1jsek.apps.googleusercontent.com',
    iosBundleId: 'com.example.estoque',
  );
}
